# Generated by Django 2.2.4 on 2019-09-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
