# Generated by Django 2.2.4 on 2019-09-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_about',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_now',
            field=models.BooleanField(default=False),
        ),
    ]
