# Generated by Django 2.2.4 on 2019-09-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190927_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=152, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='core.Post'),
        ),
    ]
